### ISSUE TITLE
Running Azure CLI on Windows

### ISSUE THREAD

**Issue by dalibormesaric** [Tyrrrz/CliWrap#102]
Thanks for a great library!

I have an issue where my code works on Ubuntu (WSL2), but not on windows.

```       
let command = "az"
let arguments = $"devops project list --org {organization}"
let output = 
    Cli.Wrap(command).WithArguments(arguments).ExecuteBufferedAsync().Task
    |> Async.AwaitTask
    |> Async.RunSynchronously
```

The error I'm getting is

```
---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CliWrap.Internal.ProcessEx.Start() in /_/CliWrap/Internal/ProcessEx.cs:line 65
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken cancellationToken) in /_/CliWrap/Command.cs:line 372
   at CliWrap.Internal.Extensions.AsyncExtensions.Select[TSource,TDestination](Task`1 task, Func`2 transform) in /_/CliWrap/Internal/Extensions/AsyncExtensions.cs:line 13
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 337
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
...
```

Before finding your library I was using ProcessStartInfo and I solved the issue by prefixing windows version with "cmd /c".

I found this solution somewhere in .net framework github issues where they discuss how Process has some cross platform limitations.

Do you have any idea to why is this happening and how to solve it without me doing some OS specific code? I was hoping this would not be an issue if I use your library.

**Comment by Tyrrrz** [comment]
Hi!

The issue is that Azure CLI is not an executable on Windows, but a `cmd` file. Because of that, you also need to provide the full path, as the `PATH` env var is only used by the system to resolve executable files.

Here's a (closed) PR to farmer that shows how to use Azure CLI with CliWrap.

Also, if you want to do `cmd /c`, it will look like this:

```csharp
var cmd = Cli.Wrap("cmd").WithArguments(new[] {"/c", "command which will be escaped automatically"});
```

**Comment by dalibormesaric** [comment]
Thanks! I like the farmer solution, so I think I will borrow it :)

Do you know why they didn't go with an exe on windows?

Also feel free to close this issue, thanks again!

**Comment by Tyrrrz** [comment]
> Do you know why they didn't go with an exe on windows?

Not a single clue. That does seem like a very weird decision.
