### ISSUE TITLE
Exception out of try-catch scope?

### ISSUE THREAD

**Issue by Nekromancer** [Tyrrrz/CliWrap#15]
Hi
I'm using CliWrap to running multiple ffmpeg (about 300 in one moment) processes all the time (each process lives for like 5 seconds). Recently i got this exception on my global error handler dispite the fact that every call to `Cli.Execute` is wrapped by try-catch. Any idea why this might be the case? It's like super rare, but still..
```
System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.Kill()
   at CliWrap.Internal.Extensions.KillIfRunning(Process process)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.TimerCallbackLogic(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at CliWrap.Internal.Extensions.KillIfRunning(Process process)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)<---

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at CliWrap.Internal.Extensions.KillIfRunning(Process process)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
```

**Comment by Tyrrrz** [comment]
Interesting. Are you supplying cancellation token?

**Comment by Nekromancer** [comment]
Yes, i'm calling it like this:

```
        public static async Task<string> HandleFfmpegDumpAsync(string arguments, TimeSpan timeout)
        {
            var cli = new Cli("ffmpeg.exe");
            var cts = new CancellationTokenSource();
            cts.CancelAfter(timeout);

            string output = "";

            try
            {
                var result = await cli.ExecuteAsync(arguments, cts.Token).ConfigureAwait(false);
                output = result.StandardError.Trim();
            }
            catch (OperationCanceledException)
            {
                Log.Warn($"Ffmpeg timeout on: {arguments}");
            }
            catch (Exception e)
            {
                Log.Warn($"ffmpeg work exception: {arguments}\nOutput: {output}\n{e}");
            }
            return output;
        }
```

**Comment by Tyrrrz** [comment]
So it looks like the task was canceled but the process could not be killed properly because access was denied (?). The reason it escapes the try/catch is because it's not `ExecuteAsync` that throws an exception but `CancellationToken`'s delegate that fires when the timeout expires. I guess ultimately, `KillIfRunning` could ignore all exceptions but it would at least be nice to know why it threw access denied. Do you have any ideas?

**Comment by Nekromancer** [comment]
I found out that windows fails to handle hundreds of short lived processes 24/7. Very rarely it's doing something silly, like this. Also ffmpeg is really messed up code..

Maybe you should give an option to override this delegate for the user to handle what to do in case of timeout? Then I could handle the exception. In my case one "zombie" process is not an issue (periodically I kill all zombie ffmpeg processes) , but unhandled exception is.

**Comment by Tyrrrz** [comment]
Overriding the delegate isn't really an option since it's internal, but I can re-throw the exception from inside `ExecuteAsync` so you can handle it in your code. Also, what exactly are you doing with ffmpeg that you can benefit from 300 active instances of it? Isn't it very CPU intensive?

**Comment by Nekromancer** [comment]
Rethrowing would be even better for me.

I'm dumping radio streams in little chunks for music recognition. It generates quite a lot of context switches but 40 cores processor can manage like 300 ffmpeg instances at once

**Comment by Tyrrrz** [comment]
Sounds pretty cool.

**Comment by Nekromancer** [comment]
There is one reason I can think of why is that exception thrown. There is a slight moment between check of process being alive and kill. If process ends in this gap - we got an exception. Just a thought, it's hard to reproduce, but it is possible in this high load scenario

**Comment by Tyrrrz** [comment]
Yeah but in that case a different exception is thrown - `InvalidOperationException` and it's actually handled already.

**Comment by Nekromancer** [comment]
Then it beats me, windows sometimes does this to me :-)

**Comment by Tyrrrz** [comment]
I uploaded a pre-release package v1.7.6-alpha which should be up on NuGet soon. Please check if it fixes both of your issues you reported.

**Comment by Nekromancer** [comment]
Yes, this new version fixes both of my issues. Thanks :-)
